schema: v1

repository:
  title: Actions
  description: Contém a abstração das actions usadas em outros projetos
  license: GPL-3
  type: infra
  topics:
    - actions
  website: https://github.com/alves-dev/actions