name: Readme Generate

on:
  push:
    branches: main

  workflow_call:
    inputs:
      repo-name:
        required: true
        type: string
    secrets:
      PERSONAL_GITHUB_TOKEN:
        required: true

jobs: 
  readme-generate:
    runs-on: ubuntu-latest
    if: github.actor != 'readme-generate'
    steps:
      - name: Trigger generate readme
        run: |
          REPO_NAME="${{ inputs.repo-name || github.repository }}"
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PERSONAL_GITHUB_TOKEN }}" \
          https://api.github.com/repos/alves-dev/infra/actions/workflows/readme-generate.yml/dispatches \
          -d '{"ref":"main", "inputs": { "repo-name": "${REPO_NAME}" }}'
