name: Sonar Scan

on:
  workflow_call:
    inputs:
      repo-name:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true

jobs: 
  scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'


      - name: Detect Java project and compile
        run: |
          if [ -f "pom.xml" ]; then
            echo "📦 Projeto Maven detectado, compilando..."
            mvn clean compile -q
          elif [ -f "build.gradle" ]; then
            echo "📦 Projeto Gradle detectado, compilando..."
            chmod +x ./gradlew
            ./gradlew build -x test --quiet
          else
            echo "⚙ Sem build Java necessário."
          fi

      - name: Sonar scanner
        run: |
          JAVA_OPTS=""
          if [ -f "pom.xml" ]; then
            JAVA_OPTS="-Dsonar.java.binaries=target"
          elif [ -f "build.gradle" ]; then
            JAVA_OPTS="-Dsonar.java.binaries=build"
          fi

          docker run --rm \
          -v "$(pwd):/usr/src" \
          sonarsource/sonar-scanner-cli \
          -Dsonar.projectKey=${{ inputs.repo-name }} \
          -Dsonar.sources=. \
          $JAVA_OPTS \
          -Dsonar.host.url=https://sonar.alves-dev.com \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Gerar resumo do SonarQube
        id: sonar-summary
        run: |
          PROJECT_KEY="${{ inputs.repo-name }}"
          DASHBOARD_URL="https://sonar.alves-dev.com/dashboard?id=${PROJECT_KEY}"
          BASE_URL="https://sonar.alves-dev.com/api/project_badges/measure?project=${PROJECT_KEY}&metric="

          cat <<EOF > sonar_result.md
          ### 📊 Resultado da Análise SonarQube

          [![Quality Gate](${BASE_URL}alert_status)](${DASHBOARD_URL})

          | Segurança | Manutenibilidade | Confiabilidade | Cobertura |
          |-----------|------------------|----------------|-----------|
          | [![Vulnerabilities](${BASE_URL}vulnerabilities)](${DASHBOARD_URL}) | [![Code Smells](${BASE_URL}code_smells)](${DASHBOARD_URL}) | [![Bugs](${BASE_URL}bugs)](${DASHBOARD_URL}) | [![Coverage](${BASE_URL}coverage)](${DASHBOARD_URL}) |
          | [![Security Rating](${BASE_URL}security_rating)](${DASHBOARD_URL}) | [![Maintainability Rating](${BASE_URL}sqale_rating)](${DASHBOARD_URL}) | [![Reliability Rating](${BASE_URL}reliability_rating)](${DASHBOARD_URL}) |  |
          | [![Security Hotspots](${BASE_URL}security_hotspots)](${DASHBOARD_URL}) | [![Technical Debt](${BASE_URL}sqale_index)](${DASHBOARD_URL}) |  |  |
          EOF

          echo "markdown<<EOF" >> $GITHUB_OUTPUT
          cat sonar_result.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Get PR Info
        uses: actions/github-script@v7
        id: pr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
              head: `${context.repo.owner}:develop`,
              base: "main"
            });

            if (prs.data.length === 0) {
              core.setFailed("❌ Nenhum PR encontrado de develop para main.");
            } else {
              const pr = prs.data[0];
              console.log(`PR encontrado: #${pr.number}`);
              core.setOutput('pr_number', pr.number);
            }

      - name: Comentar no PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = Number('${{ steps.pr.outputs.pr_number }}');
            const body = `${{ steps.sonar-summary.outputs.markdown }}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: body
            });
